### ISSUE TITLE
コマンドメッセージ機能の有効/無効 切り替え機能が欲しい

### ISSUE THREAD

**Issue by Yuukimatu** [yuttyann/CustomMessage#1]
LunaChat の変更機能と被ってしまうので
無効に出来るようにしてもらいたいです。
LunaChatの方の優先度を最大にしてもCustomMessageが優先されてしまうので
お願いします

**Comment by yuttyann** [comment]
かなり古いプラグインなので、アップデートは行わずに中身の改変だけ行いました。
該当のコマンドを削除したので期待通りの動作になるかと思います。
https://www.dropbox.com/s/6ho98dpf0y936xs/CustomMessage-7.1.jar

**Comment by Yuukimatu** [comment]
頂いたファイルをダウンロードしてpluginsに配置して起動してみたのですが、
以下のようになってしまいコマンドの実行ができませんでした。
![2021-08-17_17 55 06](https://user-images.githubusercontent.com/65291872/129695773-9992170c-7cb5-4e9b-8484-ca2180abc029.png)

**Comment by yuttyann** [comment]
plugin.ymlからコマンドの一覧を削除するのを忘れていました
https://www.dropbox.com/s/5kanpcy91dsrwts/CustomMessage-7.1.jar?dl=0

**Comment by Yuukimatu** [comment]
先ほど試してみた結果、機能することが確認できました！
ありがとうございました！！
![2021-08-17_19 37 40](https://user-images.githubusercontent.com/65291872/129711825-37d4daa5-357c-429a-8eba-a0a2017d7d0d.png)
